x-file-path: &file-path ./../../configs/services.yaml 

services:

  portainer:
    extends:
      file: *file-path
      service: portainer
    networks:
      - admin
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  admin:
    driver: bridge