services:
  base_service: &base
    init: true
    # restart: always

  portainer:
    <<: *base
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    container_name: portainer-con
    hostname: portainer
    ports:
      - "9443:9443"

  mysql:
    <<: *base
    image: mysql:oraclelinux9
    container_name: mysql-con
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: init
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    <<: *base
    image: redis:7.4.0-alpine3.20
    container_name: redis-con
    hostname: redis
    ports:
      - "6379:6379"